### ISSUE TITLE
500 Error when trying to control magic mirror

### ISSUE THREAD

**Issue by tkg61** [Bee-Mar/mmpm#29] opened 2020-05-21 01:06 UTC
Having trouble with the control center. Whenever i try to interact with magic mirror (stop, restart, etc) i get a 500 error. "Start" works but i can't stop it after and have to reboot. It seems to be an issue with "rootlogger". I am able to install and configure modules, just not interact with the MM process. Here are the errors/stack trace: 

```
Exception on /api/stop-magicmirror [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/api.py", line 322, in stop_magicmirror
    utils.stop_magicmirror()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 532, in stop_magicmirror
    kill_magicmirror_processes()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 509, in kill_magicmirror_processes
    log.logger('Killing processes associated with MagicMirror: {processes}')
TypeError: 'RootLogger' object is not callable
2020-05-20 20:44:39,704.704 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:26,817.817 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:27,077.077 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:27,097.097 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:27,102.102 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:27,106.106 INFO api - get_magicmirror_config: Retrieving MagicMirror config
Retrieving MagicMirror config
2020-05-20 20:45:27,106.106 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:27,859.859 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:45:56,348.348 INFO api - update_magicmirror_config: Saving MagicMirror config file
Saving MagicMirror config file
2020-05-20 20:45:56,350.350 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:07,250.250 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:07,528.528 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:07,543.543 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:07,549.549 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:07,557.557 INFO api - get_magicmirror_config: Retrieving MagicMirror config
Retrieving MagicMirror config
2020-05-20 20:54:07,558.558 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:08,296.296 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:20,039.039 ERROR app - log_exception: Exception on /api/stop-magicmirror [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/api.py", line 322, in stop_magicmirror
    utils.stop_magicmirror()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 532, in stop_magicmirror
    kill_magicmirror_processes()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 509, in kill_magicmirror_processes
    log.logger('Killing processes associated with MagicMirror: {processes}')
TypeError: 'RootLogger' object is not callable
Exception on /api/stop-magicmirror [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/api.py", line 322, in stop_magicmirror
    utils.stop_magicmirror()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 532, in stop_magicmirror
    kill_magicmirror_processes()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 509, in kill_magicmirror_processes
    log.logger('Killing processes associated with MagicMirror: {processes}')
TypeError: 'RootLogger' object is not callable
2020-05-20 20:54:20,042.042 INFO api - after_request: Headers being added after the request
Headers being added after the request
2020-05-20 20:54:20,052.052 ERROR app - log_exception: Exception on /api/stop-magicmirror [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/api.py", line 322, in stop_magicmirror
    utils.stop_magicmirror()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 532, in stop_magicmirror
    kill_magicmirror_processes()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 509, in kill_magicmirror_processes
    log.logger('Killing processes associated with MagicMirror: {processes}')
TypeError: 'RootLogger' object is not callable
Exception on /api/stop-magicmirror [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/api.py", line 322, in stop_magicmirror
    utils.stop_magicmirror()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 532, in stop_magicmirror
    kill_magicmirror_processes()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 509, in kill_magicmirror_processes
    log.logger('Killing processes associated with MagicMirror: {processes}')
TypeError: 'RootLogger' object is not callable
2020-05-20 20:54:20,055.055 INFO api - after_request: Headers being added after the request
Headers being added after the request

```

**Comment by Bee-Mar** [comment] 2020-05-21 13:04
@tkg61 Which version of python3 do you have?

**Comment by tkg61** [comment] 2020-05-21 13:09
I have python 3.7.3

Python 2 is also installed. Would that possibly be an issue?

**Comment by Bee-Mar** [comment] 2020-05-21 13:18
@tkg61 shoudn't be. I found where the issue is, but it'll have to wait until either later tonight, or this weekend. The logger objects seem to be resolving to different objects in different versions of python3. I've been meaning to put together tests, and this is clearly where it would have been beneficial lol

**Comment by tkg61** [comment] 2020-05-21 13:21
Ok no worries. Thanks for taking a look, This module is great!

Happy to test anything if needed.

**Comment by Bee-Mar** [comment] 2020-05-21 18:44
@tkg61 thanks! once I put a fix together, i'll let you know the branch, and you can see how it works for you

**Comment by Bee-Mar** [comment] 2020-05-22 21:39
@tkg61 well...I just looked at the error message again, and realized the bug fix was significantly more simple than what I first thought. I'll get it out in a few minutes after the pipelines are run

**Comment by Bee-Mar** [comment] 2020-05-22 22:01
@tkg61 just published the release. I'm going to go ahead close this

**Closed by Bee-Mar** 2020-05-22 22:01 UTC
Labels: bug

**Comment by tkg61** [comment] 2020-05-22 22:20
Sweet I’ll test this evening

**Comment by tkg61** [comment] 2020-05-24 01:38
Just wanted to report back that everything works. Thanks again for the help!

**Comment by Bee-Mar** [comment] 2020-05-24 01:42
Great! If you come across any other bugs, feel free to make an issue
