### ISSUE TITLE
No updates found

### ISSUE THREAD

**Issue by requiemmg** [Bee-Mar/mmpm#47] opened 2020-09-19 07:36 UTC
When I am on the command line, "mmpm update" will not find any updates ever.
Even when marketplace is refreshed from the GUI and even when an updatenotification is showing.
Using current MMPM version.

**Comment by Bee-Mar** [comment] 2020-09-19 14:47
@requiemmg this is a duplicate of a currently open issue. Please post all relevant information on the thread here:

https://github.com/Bee-Mar/mmpm/issues/45

I’ve taken a break on working on stuff lately, but will get back on these issues later this afternoon.

**Comment by Bee-Mar** [comment] 2020-09-24 10:03
@requiemmg closing this issue since it’s a duplicate

**Closed by Bee-Mar** 2020-09-24 10:03 UTC
