### ISSUE TITLE
BUG: can't install

### ISSUE THREAD

**Issue by davedudek** [Bee-Mar/mmpm#114] opened 2022-11-30 17:33 UTC
**Describe the Bug**

Is this an issue with the CLI or GUI? CLI

Is this something that should be put in the Wiki? Maybe?

Installed a fresh copy of Raspberry Pi OS 32 bit Debian Bullseye Desktop and can install Magic Mirror as described but can't get past the second line of install for  mmpm "python3 -m pip install --upgrade --no-cache-dir mmpm"

Collecting pynacl>=1.0.1
  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.5.0-cp39-cp39-linux_armv7l.whl (585 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.7/585.7 kB 1.2 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)
Collecting cffi>=1.4.1
  Downloading https://www.piwheels.org/simple/cffi/cffi-1.15.1-cp39-cp39-linux_armv7l.whl (364 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.7/364.7 kB 1.1 MB/s eta 0:00:00
Collecting pycparser
  Downloading https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 14.6 MB/s eta 0:00:00
Building wheels for collected packages: bcrypt
  Building wheel for bcrypt (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for bcrypt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-39
      creating build/lib.linux-armv7l-cpython-39/bcrypt
      copying src/bcrypt/__about__.py -> build/lib.linux-armv7l-cpython-39/bcrypt
      copying src/bcrypt/__init__.py -> build/lib.linux-armv7l-cpython-39/bcrypt
      running egg_info
      writing src/bcrypt.egg-info/PKG-INFO
      writing dependency_links to src/bcrypt.egg-info/dependency_links.txt
      writing requirements to src/bcrypt.egg-info/requires.txt
      writing top-level names to src/bcrypt.egg-info/top_level.txt
      reading manifest file 'src/bcrypt.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'requirements.txt'
      warning: no previously-included files found matching 'release.py'
      warning: no previously-included files found matching 'mypy.ini'
      warning: no previously-included files matching '*' found under directory '.github'
      warning: no previously-included files matching '*' found under directory '.circleci'
      warning: no previously-included files found matching 'src/_bcrypt/target'
      warning: no previously-included files matching '*' found under directory 'src/_bcrypt/target'
      adding license file 'LICENSE'
      writing manifest file 'src/bcrypt.egg-info/SOURCES.txt'
      copying src/bcrypt/_bcrypt.pyi -> build/lib.linux-armv7l-cpython-39/bcrypt
      copying src/bcrypt/py.typed -> build/lib.linux-armv7l-cpython-39/bcrypt
      running build_ext
      running build_rust
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install bcrypt:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Ensure you have a recent Rust toolchain installed. bcrypt requires
             rustc >= 1.56.0.
      
          Python: 3.9.2
          platform: Linux-5.15.61-v7+-armv7l-with-glibc2.31
          pip: n/a
          setuptools: 65.6.3
          setuptools_rust: 1.5.2
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.56.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bcrypt
Failed to build bcrypt
ERROR: Could not build wheels for bcrypt, which is required to install pyproject.toml-based projects
pi@magicmirror:~ $ 

**Expected behavior**

Installed mmpm successfully

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- output from `python3 --version`

Python 3.9.2

- Web Browser (firefox, chrome, safari, chromium, etc)

**MMPM Environment Settings**

- output from `mmpm env`

not installed 

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by khassel** [comment] 2022-11-30 20:23
I was already wondering if only I have problems installing this on arm32v7.

The problematic packages are `bcrypt` and `cryptography`. Both need a rust compiler for install but I had several follow-up problems after installing rust.

You can reproduce the error messages by executing `pip install bcrypt` and `pip install cryptography`.

You can see what I'm doing to build this project in [this Dockerfile](https://gitlab.com/khassel/mmpm/-/blob/master/build/Dockerfile-builder).

Short description:
- prebuilder step: get `cryptography` package on an amd64 architecture
- use this later in the arm build
- install `rustc`
- nail `bcrypt` to version `3.2.0` and cryptography to version `37.0.1` (newer versions won't work)

It took me hours to get this working. The build is very time consuming, it takes nearly 2 hours (on amd64 machines with arm emulation).

@Bee-Mar 
- is this repository still maintained?
- can you please update the dependencies to get out of this hell
- are `bcrypt` and `cryptography` really needed? If so, can they may replaced with packages including arm binaries?

Thanks,

Karsten.

**Comment by ddudekJFF** [comment] 2022-12-01 20:13
I finally got it installed after installing rustc using this command:

curl https://sh.rustup.rs -sSf | sh

**Comment by ddudekJFF** [comment] 2022-12-01 20:13
I don't see how to close out or cancel this bug report.

**Comment by JeffHochberg** [comment] 2022-12-15 06:28
I'm running MagicMirror on a Raspberry Pi 3B+ on Bullseye. I ran into the same issue when trying to install mmpm.

I started down the path of installing rustc, but it didn't appear to be necessary. Then I tried running the rustup script per @redsoxdad comment.

```
curl https://sh.rustup.rs -sSf | sh
```
I received an error since I already had rustc installed.

I ended up going back to what @khassel wrote - but I streamlined the process. I interpreted the term "nail" to mean "install a specific version. Good thing I have my trusty thesaurus for people that assume everyone knows what they mean. :-)

```
pip install -Iv bcrypt==3.7.0
pip install -Iv cryptography==37.0.1
pip install mmpm
```

That seemed to do the trick!

Additionally - any time I logged in after installing mmpm, I received the following message:

```
-bash: register-python-argcomplete: command not found
```

Turns out you have to install python3-argcomplete for the bash completion routine mmpm adds to .bashrc to execute successfully.

```
sudo apt install python3-argcomplete
```

**Comment by Bee-Mar** [comment] 2023-01-07 16:46
@khassel this is going to be resolved shortly. The `webssh` package requires bcrypt. I'm just going to remove it from the application since this doesn't seem like a feature people are using anyway

**Comment by Bee-Mar** [comment] 2023-01-15 16:11
@khassel the latest version, 2.15, is now available and `webssh` has been removed. This issue should be alleviated

**Comment by Bee-Mar** [comment] 2023-01-15 16:24
@khassel Actually, do not use 2.15. That version is going to be removed from PyPi. 2.16 is running through the pipeline now. There was a typo in an API url, which has been corrected. The new version should be available shortly

**Comment by Bee-Mar** [comment] 2023-01-15 16:38
@khassel version 2.16 is now available

**Comment by khassel** [comment] 2023-01-15 21:35
@Bee-Mar 

any idea to `+ Initializing MagicMirror 3rd party packages database FATAL: 'list' object has no attribute 'find_all'` when calling `mmpm db -r`?

**Comment by Bee-Mar** [comment] 2023-01-15 21:42
@khassel looking into it now. I'm getting the same error

**Comment by Bee-Mar** [comment] 2023-01-15 22:15
@khassel the fix is incoming, and the new version (2.17) is getting run through the pipeline now. Something I've been meaning to do is add proper unit tests (plus rework a whole bunch of the codebase to be cleaner), and that seems to be needed

**Comment by Bee-Mar** [comment] 2023-01-15 22:20
@khassel 2.17 is available now

**Comment by khassel** [comment] 2023-01-15 22:29
Thanks!

> to do is add proper unit tests

would be helpful ...

My artifact builds for `amd64` and `arm64` did run now, `arm` needs ~30 min. I don't expect more problems.

**Comment by khassel** [comment] 2023-01-16 21:45
One thing concerning the WebUI.

With version 2.14 if I call `http://localhost:7890` mmpm is displayed and the url in the browser stays the same.

With version 2.17 if I call `http://localhost:7890` mmpm is displayed but the url in the browser turns to `http://localhost:7890/static/static/`. Hitting F5 now results in a `404`. There are also some errors in the dev console not finding some files.

The nginx config concerning ports 7890/91 is unchanged between the versions, so may something with the gui updates?

Can you reproduce this?

**Comment by bgnzo818** [comment] 2023-01-19 04:51
@khassel  - I'm having this same issue running 2.17.

**Comment by Bee-Mar** [comment] 2023-01-19 13:56
@khassel @bgnzo818 I was able to reproduce this and will resolve it today

**Comment by Bee-Mar** [comment] 2023-01-20 17:23
@khassel the fix is incoming. Just shoring up the dependency versions

**Comment by Bee-Mar** [comment] 2023-01-21 17:50
@khassel still working on resolving all the python 3.x compatibility

**Comment by Bee-Mar** [comment] 2023-01-23 02:23
@khassel getting things prepped now

**Comment by Bee-Mar** [comment] 2023-01-23 02:37
@JeffHochberg @davedudek @khassel @bgnzo818 a new version is available and this should solve the problems

**Comment by khassel** [comment] 2023-01-23 21:13
Thanks!

Docker images for 3.0 are released.

**Comment by bgnzo818** [comment] 2023-01-23 21:25
thanks! This worked for me.

**Comment by Bee-Mar** [comment] 2023-12-18 06:32
@bgnzo818 @davedudek @JeffHochberg version 4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)

**Closed by Bee-Mar** 2023-12-18 06:32 UTC
