### ISSUE TITLE
BUG: Rotate feature not working

### ISSUE THREAD

**Issue by josdemmers** [Bee-Mar/mmpm#44] opened 2020-08-29 16:22 UTC
**Describe the Bug**

Using the rotate feature in the web interface throws an error.
`Error Code: 500
Message: Http failure response for http://192.168.1.149:7890/api/raspberrypi/rotate-screen: 500 INTERNAL SERVER ERROR`

Log file mentions the following exception:
`Exception on /api/raspberrypi/rotate-screen [POST]`

**To Reproduce**
1. Go to the web interface and goto Control Center.
2. Click on Rotate Screen.
3. See error

**Expected behavior**
I expect the screen to rotate.

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- output from `python3 --version`
Python 3.7.3

- Web Browser (firefox, chrome, safari, chromium, etc)
Firefox

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`
[mmpm-logs-2020-7-6.zip](https://github.com/Bee-Mar/mmpm/files/5145537/mmpm-logs-2020-7-6.zip)

- your MagicMirror `config.js`
[config.js.txt](https://github.com/Bee-Mar/mmpm/files/5145539/config.js.txt)

**Comment by Bee-Mar** [comment] 2020-08-29 20:59
@josdemmers well, the problem is easily fixable here. I'll push a fix to develop then to master shortly

**Comment by Bee-Mar** [comment] 2020-08-29 22:25
@josdemmers closing this. The fix has been pushed, and you can download the new version using `pip3 install --upgrade --no-cache-dir mmpm`

**Closed by Bee-Mar** 2020-08-29 22:25 UTC
