### ISSUE TITLE
Error 502 - Bad Gateway

### ISSUE THREAD

**Issue by djochem-keyONE** [Bee-Mar/mmpm#85] opened 2022-01-19 09:52 UTC
Regarding the already closed issue #40 I am experiencing the same issues with current version of MMPM on every reboot.
What fixed it for me, was editing the mmpm.conf replacing the "localhost" entries with "127.0.0.1" as suggested in the last post on that issue.

First assumed, that maybe active IPv6 on the network adapters would cause this issue, but even when disabling IPv6 the issue persists.

Maybe there is any other solution instead of modifying mmpm.conf?

**Comment by Bee-Mar** [comment] 2022-01-19 13:19
@djochem-keyONE after upgrade did you re-run 'mmpm install --gui'?

**Comment by djochem-keyONE** [comment] 2022-01-19 13:24
No, I had this issue on a completely fresh install of MagicMirror with MMPM. I installed MM and MMPM with the corresponding manuals. Everything worked fine until a reboot. I tried re-run 'mmm install --gui' and also re-installing MMPM but nothing helped. That's why I came through google to issue #40 :-)
After changing the mmpm.conf like mentioned in my first post, MMPM comes up as expected after a reboot and is working fine.

**Comment by unclecracker** [comment] 2022-02-03 12:46
I can confirm the issue and I am able to reproduce it by the following steps:

I have an RPI 3 B with x64 RaspianOS https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64.zip

- Fresh setup SD and boot to desktop
- Initial OS Setup assistant, Wifi, updates
- Locale en,US,UTF-8
- apt update / upgrade
- sudo apt install libffi-dev nginx-full -y
- python3 -m pip install --upgrade --no-cache-dir mmpm
- echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
- reboot
- mmpm install --magicmirror (default path, pm2 and disable screensaver)
- mmpm --guided-setup result:
`{
  "MMPM_MAGICMIRROR_ROOT": "/home/pi/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://127.0.0.1:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}`
- edit config.js -> adress: 127.0.0.1 and ipWhitelist: []
- install mpmm module and edit config.js accordingly

This does work until next reboot, there I just get the 502 from nginx.

This can be fixed by disabling IPv6 on the raspberry for the used Interface, or for all Interfaces:
Insert `net.ipv6.conf.all.disable_ipv6=1` or `net.ipv6.conf.<interface>.disable_ipv6=1` to `/etc/sysctl.conf` and `service procps reload` to `/etc/rc.local` right before `exit 0`.

So it seems to be an issue with RPIs that have an active IPv6 adress as the other thread https://github.com/Bee-Mar/mmpm/issues/40 already suggested.

**Comment by prandleman** [comment] 2022-02-26 17:42
> I can confirm the issue and I am able to reproduce it by the following steps:
> 
> I have an RPI 3 B with x64 RaspianOS https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64.zip
> 
> * Fresh setup SD and boot to desktop
> * Initial OS Setup assistant, Wifi, updates
> * Locale en,US,UTF-8
> * apt update / upgrade
> * sudo apt install libffi-dev nginx-full -y
> * python3 -m pip install --upgrade --no-cache-dir mmpm
> * echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
> * reboot
> * mmpm install --magicmirror (default path, pm2 and disable screensaver)
> * mmpm --guided-setup result:
>   `{ "MMPM_MAGICMIRROR_ROOT": "/home/pi/MagicMirror", "MMPM_MAGICMIRROR_URI": "http://127.0.0.1:8080", "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror", "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".", "MMPM_IS_DOCKER_IMAGE": false }`
> * edit config.js -> adress: 127.0.0.1 and ipWhitelist: []
> * install mpmm module and edit config.js accordingly
> 
> This does work until next reboot, there I just get the 502 from nginx.
> 
> This can be fixed by disabling IPv6 on the raspberry for the used Interface, or for all Interfaces: Insert `net.ipv6.conf.all.disable_ipv6=1` or `net.ipv6.conf.<interface>.disable_ipv6=1` to `/etc/sysctl.conf` and `service procps reload` to `/etc/rc.local` right before `exit 0`.
> 
> So it seems to be an issue with RPIs that have an active IPv6 adress assigned as the other thread #40 already suggested.

Thank you this was really annoying.

**Comment by Bee-Mar** [comment] 2022-05-02 10:24
Does the IPV6 fix still work for all of you? If so, I'll add that as a suggestion to the wiki

**Closed** 2022-05-03 12:46 UTC
