### ISSUE TITLE
AttributeError: module 'pip' has no attribute 'main'

### ISSUE THREAD

**Issue by shahrukh-alizai** [Bee-Mar/mmpm#7] opened 2019-11-18 18:01 UTC
Using Python 3 on Raspbian latest. Installed `mmpm` package via this command:
`git clone https://github.com/Bee-Mar/mmpm.git && cd mmpm && make install`

Expected results:
- Everything works fine

Actual Results:
- Getting error: `AttributeError: module 'pip' has no attribute 'main'`

**Comment by xadamxk** [comment] 2019-11-21 22:28
What version of pip do you have installed?
```
pip --version
```

Not the ideal solution, but...
I believe version 10 requires slight changes for anything using v9 or lower.
If you have 10 installed, try downgrading/upgrading to the most recent version 9.

**Comment by Bee-Mar** [comment] 2019-11-23 17:21
@xadamxk yes, this is commonly caused by an out of date version of `pip.` 

@shahrukh-alizai  Try upgrading your version of `pip` with `pip install --user --upgrade pip;`, and you may need to do that for `pip3` as well

**Comment by vKnmnn** [comment] 2019-12-09 20:12
Having the same issue on raspbian 10 and on archlinux, even  after upgrading pip3 and pip2 to version 19.3.1, so that doesn't seem to help.

**Comment by Bee-Mar** [comment] 2019-12-14 19:32
Have you tried installing the latest version of the package? If not, try cloning the repo, and re-installing.

**Comment by vKnmnn** [comment] 2019-12-21 16:20
pip 19.3.1 is the latest stable release. Or did you mean the latest mmpm package?

**Comment by Bee-Mar** [comment] 2019-12-23 12:13
@vKnmnn the latest mmpm package, sorry, didn't clarify

**Comment by accountnumber3** [comment] 2019-12-30 03:45
Fresh install, same issue. Root or nonroot doesn't matter.

```
[22:43][mmpm]# mmpm
Traceback (most recent call last):
  File "/root/.local/bin/mmpm", line 11, in <module>
    load_entry_point('mmpm==0.34', 'console_scripts', 'mmpm')()
  File "/root/.local/lib/python3.6/site-packages/mmpm-0.34-py3.6.egg/mmpm/__main__.py", line 12, in main
AttributeError: module 'mmpm' has no attribute 'main'
[22:43][~]# python3 --version
Python 3.6.9
[22:44][~]# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

**Comment by testbughub** [comment] 2019-12-30 14:54
> Fresh install, same issue. Root or nonroot doesn't matter.
> 
> ```
> [22:43][mmpm]# mmpm
> Traceback (most recent call last):
>   File "/root/.local/bin/mmpm", line 11, in <module>
>     load_entry_point('mmpm==0.34', 'console_scripts', 'mmpm')()
>   File "/root/.local/lib/python3.6/site-packages/mmpm-0.34-py3.6.egg/mmpm/__main__.py", line 12, in main
> AttributeError: module 'mmpm' has no attribute 'main'
> [22:43][~]# python3 --version
> Python 3.6.9
> [22:44][~]# pip3 --version
> pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
> ```

+1 here.

**Comment by Bee-Mar** [comment] 2019-12-31 02:14
Try re-cloning the repo now. I found the issue, and it should be good...hopefully lol

@testbughub  @accountnumber3 @vKnmnn

**Comment by testbughub** [comment] 2019-12-31 08:09
It now works. Thanks!
Just a tought; Could you format the output for -a so it can be displayed on smaller screens?
I use 1366x768, and it looks like everything is set to work on larger displays.

**Comment by accountnumber3** [comment] 2019-12-31 15:25
Works for me!

**Comment by Bee-Mar** [comment] 2020-01-01 04:42
@testbughub I’ll see what I can do. It may require me to format the text so it’s more condensed. The tabulate package is a bit restrictive on the formatting width

**Comment by Bee-Mar** [comment] 2020-01-01 04:43
I’ll go ahead and close this issue now since it appears to be working for the people that had the issues

**Closed by Bee-Mar** 2020-01-01 04:43 UTC
